<?php
/**
 * @file
 * cseu_features_structure.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function cseu_features_structure_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Working Group 1',
    'description' => 'WG1: Ensure scientific quality of Citizen Science',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '05015bf1-5fb3-4482-9f88-f40d2d6ec73d',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'innovation',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0c17c14e-bad2-4e35-bab1-65fa01cb2ffc',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'citizen science',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '131184bd-11ee-4614-a6da-9dcceb961961',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'policy',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1545a72f-0b82-4e11-a90f-554262a3fef9',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'STM Coordinator',
    'description' => 'STM Coordinator',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1e04b719-ef6f-4381-8cc1-4ff1bb769852',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'Working Group 5',
    'description' => 'WG5: Improve data standardization and interoperability',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '269be0f2-b8f7-4022-b7d8-d3906234b64b',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'Chairs',
    'description' => 'Chairs',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3059e640-8ccf-48a2-8fb9-dcefbc6320a3',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'Early-Stage Researcher Representative',
    'description' => 'Early-Stage Researcher Representative',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3bf96995-6f2c-47be-b7af-4c29b6477449',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'Management Committee Substitute',
    'description' => 'Management Committee Substitute',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3f56a06e-3958-43a6-9e34-c567689ae09f',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'Working Group 6',
    'description' => 'WG6: Overaching - Cross-WG-Synthesis and overarching measures',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4148aaad-b84b-44d1-bb98-c7f843fc926c',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'Europe',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '604be5a6-e17a-4c8f-a0ac-bb103b2a1b6c',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Working Group 4',
    'description' => 'WG4: Enhance the role of CS for civil society',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6a37cb77-d0f7-4ec6-830d-671a9b30b696',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'education',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6ba12a2d-bab3-4609-910c-b2547f49693b',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Management Committee',
    'description' => 'Management Committee',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '90fb546d-08ae-4ff0-a3b1-ee14c7ea81ae',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'Co-Chairs',
    'description' => 'Co-Chairs',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '95c59c1d-2614-4456-9f90-2b9caa7cd670',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'research',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '976d7835-b711-49b6-a6db-8253378d3e49',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Working Group 3',
    'description' => 'WG3: Improve society-science-policy interface',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'aad7afc5-8ce5-4bc1-87b1-86674b4550f7',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'Working Group 2',
    'description' => 'WG2: Develop synergies with education',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c2e5383f-9f5e-48b3-b3c4-6b9e829d2152',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'Secondary Proposer',
    'description' => 'Secondary Proposer',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'db266d87-7f87-4199-b6ab-6a8d1aa653dc',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'Equal Opportunity Officer',
    'description' => 'Equal Opportunity Officer',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fd6760c9-3de5-4941-8342-f76da77dd1bd',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'External Liaison Officer',
    'description' => 'External Liaison Officer',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ff30412b-d215-48b5-bacb-06fc6b85561c',
    'vocabulary_machine_name' => 'newsletter',
  );
  return $terms;
}
