<?php
/**
 * @file
 * cseu_features_structure.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function cseu_features_structure_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'innovation',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0c17c14e-bad2-4e35-bab1-65fa01cb2ffc',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'citizen science',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '131184bd-11ee-4614-a6da-9dcceb961961',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'policy',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1545a72f-0b82-4e11-a90f-554262a3fef9',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Working Group 6',
    'description' => 'WG6: Overaching - Cross-WG-Synthesis and overarching measures',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3724b5c0-8cd4-48c6-858d-945d6c651893',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'Secondary Proposer',
    'description' => 'Secondary Proposer',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4e5aa17c-faff-4e6a-b6f2-b1c62c18077c',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'Europe',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '604be5a6-e17a-4c8f-a0ac-bb103b2a1b6c',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Working Group 3',
    'description' => 'WG3: Improve society-science-policy interface',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '68fff7e5-e7fa-49e6-bcb7-8c590f57e327',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'education',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6ba12a2d-bab3-4609-910c-b2547f49693b',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Early-Stage Researcher Representative',
    'description' => 'Early-Stage Researcher Representative',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '723f0243-c863-4a50-a877-31c666d6d0bf',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'Working Group 5',
    'description' => 'WG5: Improve data standardization and interoperability',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7c7c647b-d2b2-480d-a51d-d5e5c4464404',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'Chairs',
    'description' => 'Chairs',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8b08d935-1b86-48d4-9e7d-c517ad40e35e',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'Management Committee Substitute',
    'description' => 'Management Committee Substitute',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '905e7ba4-8daf-4f66-8695-bbb7639d0289',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'Equal Opportunity Officer',
    'description' => 'Equal Opportunity Officer',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '90edc6e2-7098-4b6e-ac71-25f5141ac423',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'research',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '976d7835-b711-49b6-a6db-8253378d3e49',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Co-Chairs',
    'description' => 'Co-Chairs',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '98d2e446-b499-451e-85ff-515fb68b73bb',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'STM Coordinator',
    'description' => 'STM Coordinator',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'adcb3535-7147-4b6f-8285-38ab5fa8c40d',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'Working Group 2',
    'description' => 'WG2: Develop synergies with education',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b08438f3-3da9-4b84-8298-4003d206b996',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'Management Committee',
    'description' => 'Management Committee',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c40e5736-7df4-4a1d-9e02-df73923373fe',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'External Liaison Officer',
    'description' => 'External Liaison Officer',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e35674ea-dc91-4d04-8b3d-6cdb1961da4c',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'Working Group 1',
    'description' => 'WG1: Ensure scientific quality of Citizen Science',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e3d79656-e0d3-4cf6-aa31-409e580ee8f3',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'Working Group 4',
    'description' => 'WG4: Enhance the role of CS for civil society',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e83d3680-5650-463e-bbee-230471dbafd0',
    'vocabulary_machine_name' => 'newsletter',
  );
  return $terms;
}
