<?php
/**
 * @file
 * cseu_features_structure.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function cseu_features_structure_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'citizen science',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0ba78837-762e-4fe5-a328-8594dfa95154',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'innovation',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0c17c14e-bad2-4e35-bab1-65fa01cb2ffc',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'citizen science',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '131184bd-11ee-4614-a6da-9dcceb961961',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'policy',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1545a72f-0b82-4e11-a90f-554262a3fef9',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Newsletter Core Group',
    'description' => 'Chairs, Co-Chairs, STM Coordinator, Early Stage Representative, Equal Opportunity Officer, External Liason Officer, Marisa Ponti',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2a6cd0bb-a4eb-4a12-8163-7be215f12504',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'Newsletter Working Group 1',
    'description' => 'WG1: Ensure scientific quality of Citizen Science',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3461fb0d-1e83-4dd2-93f5-819308f8c0ac',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'Newsletter Management Committee Substitute',
    'description' => 'Newsletter Management Committee Substitute',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '364ad312-69b8-4ac0-becf-a5a406f8c728',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'education',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '41c2686a-01b0-44fb-8308-89506fe3f07d',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Europe',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '604be5a6-e17a-4c8f-a0ac-bb103b2a1b6c',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'policy',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '69c7bc1a-a920-469e-a93f-bf36582b7093',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'education',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6ba12a2d-bab3-4609-910c-b2547f49693b',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Newsletter Working Group 3',
    'description' => 'WG3: Improve society-science-policy interface',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7040e70f-8d18-4301-bcc1-468e286af966',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'Newsletter Management Committee',
    'description' => 'Newsletter Management Committee',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '75fbe5f1-0c0b-429a-b75d-55e2121ea02b',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'research',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '976d7835-b711-49b6-a6db-8253378d3e49',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'research',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '996fea90-9cdb-48d5-9b26-b4f0041196fd',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Newsletter Members',
    'description' => 'Newsletter ALL Members',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bcce246c-4dc3-4f7e-af0e-1d7fa2af68c9',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'Newsletter Co-Chairs',
    'description' => 'Newsletter Co-Chairs',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bff166a0-bc54-4fde-9fd5-d337d7e2dd35',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'Newsletter Working Group 6',
    'description' => 'WG6: Overaching - Cross-WG-Synthesis and overarching measures',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cfb1f191-b7b9-40ad-899a-5c75e3105b7f',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'Newsletter Working Group 4',
    'description' => 'WG4: Enhance the role of CS for civil society',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'dbf70826-c0bd-400f-8726-eeb54264324f',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'Newsletter Working Group 2',
    'description' => 'WG2: Develop synergies with education',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e3680f16-d3e3-47c3-858c-07c1075ee7f4',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'innovation',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e5649622-4e50-42a9-9d98-2a37970d8ff8',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Newsletter Secondary Proposer',
    'description' => 'Newsletter Secondary Proposer',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ef7917b2-db36-42a8-be74-25326cffe748',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'Newsletter Chairs',
    'description' => 'Newsletter Chairs',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f2c08be9-03bf-414b-9000-b1fd83936a03',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'Newsletter Working Group 5',
    'description' => 'WG5: Improve data standardization and interoperability',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fae487b4-946a-44cc-a115-bdc6ff7e0776',
    'vocabulary_machine_name' => 'newsletter',
  );
  $terms[] = array(
    'name' => 'Europe',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ff2758bc-009b-4e91-9ecf-a4566dec5bad',
    'vocabulary_machine_name' => 'tags',
  );
  return $terms;
}
